Vagrant.configure(2) do |config|
  config.vm.define "vb" do |vb|
    vb.vm.box = "ubuntu/trusty64"
    vb.vm.network "forwarded_port", guest: 80, host: 8080
    vb.vm.provision "ansible" do |ansible|
     ansible.playbook = "apache/apache.yml"
    end
  end
end
