BOX_IMAGE = "ubuntu/trusty64"

Vagrant.configure(2) do |config|

  config.vm.define "Equipo1" do |vb|
    config.vm.provider :virtualbox do |vb|
      vb.memory = 1024
      vb.cpus = 2
    end
    vb.vm.box = BOX_IMAGE
    vb.vm.hostname = "Equipo1"
    vb.vm.network "public_network", bridge: "ens32", ip: "192.168.1.201"
    vb.vm.provision "ansible" do |ansible|
     ansible.playbook = "ansible/web/apache/apache.yml"
    end
  end

  config.vm.define "Equipo2" do |vb|
    config.vm.provider :virtualbox do |vb|
      vb.memory = 512
      vb.cpus = 2
    end
    vb.vm.box = BOX_IMAGE
    vb.vm.hostname = "Equipo2"
    vb.vm.network "public_network", bridge: "ens32", ip: "192.168.1.202"
    vb.vm.provision "ansible" do |ansible|
     ansible.playbook = "ansible/web/apache/nginx.yml"
    end
  end

  vb.vm.provision "ansible" do |ansible|
   ansible.playbook = "ansible/bd/mysql/mysql.yml"
  end

end
